apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-react-kubernetes
spec:
  replicas: 1 # Number of replicas to deploy
  selector:
    matchLabels:
      app: deploy-react-kubernetes
  template:
    metadata:
      labels:
        app: deploy-react-kubernetes
    spec:
      containers:
        - name: deploy-react-kubernetes
          image: houssamelbakkouri/deploy-react-kubernetes
          ports:
            - containerPort: 3000 # Port that the React app listens on
---
apiVersion: v1
kind: Service
metadata:
  name: deploy-react-kubernetes-service
spec:
  type: NodePort
  selector:
    app: deploy-react-kubernetes
  ports:
    - name: my-app
      port: 3000
      targetPort: 3000